import os
import sys
import yaml
import structlog
import pandas as pd
from pathlib import Path
from datetime import datetime

from packages.strategy_foundry.factory.generator import StrategyGenerator
from packages.strategy_foundry.backtest.engine import BacktestEngine
from packages.strategy_foundry.backtest.walkforward import WalkForward
from packages.strategy_foundry.selection.ranker import Ranker
from packages.strategy_foundry.selection.promote import Promoter
from packages.strategy_foundry.data.loader import DataLoader
from packages.strategy_foundry.adapters.core_costs import get_default_costs
from packages.strategy_foundry.live.signal_publisher import SignalPublisher

logger = structlog.get_logger(__name__)

# Config Paths
BASE_DIR = Path(__file__).parent
CONFIG_PATH = BASE_DIR / "configs/foundry.yaml"
RESULTS_DIR = BASE_DIR / "results"

def load_config():
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)

def run():
    logger.info("Starting Strategy Foundry Hourly Run")
    config = load_config()

    # Mode Detection
    fast_mode = os.getenv("FAST_MODE", "0") == "1"

    candidates_count = config["defaults"]["candidates_fast_mode"] if fast_mode else config["defaults"]["candidates_per_run"]
    folds = config["defaults"]["folds_fast"] if fast_mode else config["defaults"]["folds"]

    # 1. Data Loading
    loader = DataLoader()
    instruments = ["NIFTY"] # TODO: Iterate SENSEX too
    timeframes = config["defaults"]["timeframes"] # ["5m", "15m"]

    run_ts = int(datetime.now().timestamp())
    run_dir = RESULTS_DIR / "runs" / str(run_ts)
    run_dir.mkdir(parents=True, exist_ok=True)

    generator = StrategyGenerator()
    candidates = generator.generate_candidates(n=candidates_count)

    # Save candidates
    with open(run_dir / "candidates.json", "w") as f:
        f.write(pd.Series([c.to_json() for c in candidates]).to_json()) # Simple list dump

    ranker = Ranker(config)
    promoter = Promoter(config)

    leaderboards = {}

    for tf in timeframes:
        logger.info(f"Processing {tf}")
        # Fetch Data
        try:
            df = loader.fetch_data("NIFTY", tf, lookback_days=60 if tf == "5m" else 120)
        except Exception as e:
            logger.error(f"Data fetch failed for {tf}", error=str(e))
            continue

        costs = get_default_costs()
        engine = BacktestEngine(df, costs)
        wf = WalkForward(df, engine, folds=folds)

        results = []
        for cand in candidates:
            # Backtest & Walkforward
            res = wf.run(cand)
            if res["status"] == "ok":
                results.append({
                    "candidate": cand,
                    "metrics": res,
                    "folds": res["folds"]
                })

        # Rank
        ranked_df = ranker.rank(results, tf)
        if not ranked_df.empty:
            ranked_df.to_csv(run_dir / f"leaderboard_{tf}.csv")
            leaderboards[tf] = ranked_df

            # Promote Champion (Top 1)
            # Only in FULL mode usually, but code allows fast mode too if needed.
            # But prompt says "DO NOT promote champions in FAST_MODE".
            if not fast_mode and len(ranked_df) > 0:
                top = ranked_df.iloc[0]
                promoter.promote(top, tf)

    # Live Signal Publish
    # Only if NOT fast mode? Or always?
    # Usually we want live signals to be generated by the periodic run.
    # But if fast_mode is on (PR), we shouldn't publish live signals to the artifact that ops uses.
    # But for testing, we might want to see if it works.
    # The requirement says "Ship as a PR... publish live signal JSON during market hours".
    # I will run it, but maybe mark status as TEST if fast_mode.

    if not fast_mode:
        SignalPublisher().run()
    else:
        logger.info("Fast Mode: Skipping Live Signal Publish")

    logger.info("Foundry Run Complete", run_id=run_ts)

if __name__ == "__main__":
    run()
