#!/usr/bin/env python3
"""
Monday Trading Plan Generator
=============================

Convenes the Level 7 HiveMind Council to generate a pre-market trading plan
for Monday. The council simulates Monday pre-market conditions, debates strategy,
and locks in configuration before the opening bell.
"""

import sys
import os
import json
from datetime import datetime
from dotenv import load_dotenv

# Ensure project root is in path
sys.path.append(os.getcwd())

from packages.core.hivemind.swarm import HiveMindSwarm

def main():
    load_dotenv()
    
    print("\n" + "="*70)
    print("🧠 HIVEMIND: INITIATING MONDAY PRE-MARKET STRATEGY SESSION")
    print("="*70)
    print()
    
    # 1. Establish Context (Simulated Pre-Market State)
    # We feed the HiveMind with expected Monday conditions
    monday_context = {
        "timestamp": datetime.now().isoformat(),
        "day": "Monday",
        "market_status": "PRE_MARKET",
        "vix": 14.5,  # Expecting slightly elevated VIX at open
        "trend": "SIDEWAYS_BULLISH",  # Recent bias
        "events": "Global Markets Mixed",
        "pnl": 0.0,  # Fresh week
        "margin_used": 0,
        "net_delta": 0,
        "market_regime": "UNKNOWN",  # Will be determined by MarketAgent
        "strategy_metrics": {
            # Base confidence from SME/History
            "trend_credit_spread": {"win_rate": 0.55, "recent_performance": "FLAT"},
            "intraday_short_strangle": {"win_rate": 0.72, "recent_performance": "STRONG"}
        },
        "avg_slippage": 0.0,
        "chase_savings": 0.0,
        "portfolio_risk": {
            "daily_pnl": 0.0,
            "portfolio_heat_pct": 0.0,
            "available_margin": 1000000.0,
            "margin_utilization_pct": 0.0,
            "net_liquid": 1000000.0,
            "used_margin": 0.0
        },
        "execution_stats": {
            "avg_slippage_bps": 0.0,
            "avg_slippage": 0.0,
            "avg_limit_chase_savings_bps": 0.0,
            "chase_savings": 0.0,
            "fill_rate": 1.0,
            "avg_order_latency_ms": 0.0
        }
    }
    
    # 2. Convene The Council
    config_path = "configs/kite_day1_live.yaml"
    if not os.path.exists(config_path):
        config_path = "configs/kite_canary_live.yaml"
    
    hive = HiveMindSwarm(config_path)
    
    print("📡 MarketAgent is analyzing Global Cues...")
    print("🎯 StrategyAgent is assessing Entry Windows...")
    print("🛡️  RiskAgent is evaluating Weekend Gap Risk...")
    print("⚡ ExecutionAgent is calibrating Slippage Models...")
    print("📚 AnalystAgent is recalling Historical Patterns...")
    print("📊 AllocatorAgent is drafting Capital Distribution...")
    print("⚖️  RefereeAgent is drafting the Directive...")
    print()
    
    report = hive.run_council_meeting(monday_context)
    
    # 3. Generate The Plan Document
    regime = report.get('market_analysis', {}).get('regime', 'UNKNOWN')
    if not regime or regime == 'UNKNOWN':
        regime = report.get('context_snapshot', {}).get('regime', 'UNKNOWN')
    
    risk_analysis = report.get('risk_analysis', {})
    defcon = risk_analysis.get('defcon_level', 5)
    if isinstance(defcon, str):
        # Convert "DEFCON_3" to 3
        try:
            defcon = int(defcon.split('_')[-1])
        except:
            defcon = 5
    
    market_insight = report.get('market_analysis', {}).get('insight', 'No specific insight.')
    if not market_insight or market_insight == 'No specific insight.':
        market_insight = report.get('market_analysis', {}).get('summary', market_insight)
    
    strategy_recs = report.get('strategy_recs', {})
    if isinstance(strategy_recs, dict):
        recommendations = strategy_recs.get('recommendations', {})
    else:
        recommendations = strategy_recs
    
    plan = f"""# 🛡️ MONDAY BATTLE PLAN (Level 7 Directive)

**Generated by HiveMind Swarm**  
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}  
**Status:** PRE-MARKET PLANNING SESSION

---

## 1. Market Assessment (MarketAgent)

- **Regime Outlook:** `{regime}`
- **Volatility Context:** VIX {monday_context['vix']}
- **Trend Bias:** {monday_context['trend']}
- **Insight:** {market_insight}

---

## 2. Strategic Directives (StrategyAgent)

**Recommendations:**
```json
{json.dumps(recommendations, indent=2) if recommendations else "No specific recommendations"}
```

---

## 3. Risk Protocols (RiskAgent)

- **DEFCON Level:** {defcon} / 5
- **Weekend Gap Protocol:** {"ACTIVE" if defcon < 4 else "STANDARD"}
- **Max Allocation:** {risk_analysis.get('max_allowed_allocation', '1.0')}x
- **Risk Assessment:** {risk_analysis.get('summary', risk_analysis.get('assessment', 'Standard risk parameters'))}

---

## 4. Execution Readiness (ExecutionAgent)

- **Slippage Model:** {report.get('exec_analysis', {}).get('slippage_model', 'Standard')}
- **Execution Strategy:** {report.get('exec_analysis', {}).get('strategy', 'Limit Chase Active')}
- **Latency Target:** {report.get('exec_analysis', {}).get('target_latency_ms', 'N/A')} ms

---

## 5. Historical Context (AnalystAgent)

{report.get('historical_context', {}).get('summary', 'No historical patterns identified for this scenario.')}

---

## 6. Capital Allocation (AllocatorAgent)

The following weights have been **ENFORCED** for Monday Open:

"""
    
    allocations = report.get('approved_allocations', {})
    if not allocations:
        # Fallback to allocation proposal if approved_allocations not set
        alloc_proposal = report.get('allocation_proposal', {})
        if isinstance(alloc_proposal, dict):
            allocations = alloc_proposal.get('allocations', {})
        else:
            allocations = {}
    
    if allocations:
        for strat, weight in allocations.items():
            plan += f"- **{strat}:** {float(weight)*100:.1f}%\n"
    else:
        plan += "- *No allocation changes recommended*\n"
    
    plan += f"""
---

## 7. Final Verdict (RefereeAgent)

**Directive:** `{report.get('final_directive', 'PROCEED')}`

> "{report.get('reasoning', 'Proceed with caution. Monitor market conditions closely.')}"

**Voting Summary:**
{json.dumps(report.get('voting_summary', {}), indent=2) if report.get('voting_summary') else "Unanimous consensus"}

---

## 8. Action Items

✅ Configuration `{config_path}` has been updated with HiveMind directives  
✅ System ready for 09:15 AM Launch  
✅ All agents aligned on Monday strategy

---

## 9. Agent Transparency Report

### MarketAgent Full Analysis
```json
{json.dumps(report.get('market_analysis', {}), indent=2)}
```

### StrategyAgent Full Recommendations
```json
{json.dumps(report.get('strategy_recs', {}), indent=2)}
```

### RiskAgent Full Assessment
```json
{json.dumps(report.get('risk_analysis', {}), indent=2)}
```

### ExecutionAgent Full Analysis
```json
{json.dumps(report.get('exec_analysis', {}), indent=2)}
```

### AnalystAgent Full Context
```json
{json.dumps(report.get('historical_context', {}), indent=2)}
```

### AllocatorAgent Full Proposal
```json
{json.dumps(report.get('allocation_proposal', {}), indent=2)}
```

---

**End of Battle Plan**

*Generated by AITRAPP Level 7 HiveMind Swarm*
"""
    
    print(plan)
    
    # Save Plan
    os.makedirs("docs", exist_ok=True)
    plan_path = "docs/MONDAY_PLAN.md"
    with open(plan_path, "w") as f:
        f.write(plan)
    
    print(f"\n{'='*70}")
    print(f"📄 Official Plan saved to: {plan_path}")
    print(f"{'='*70}\n")
    
    # Print summary
    print("📊 QUICK SUMMARY:")
    print(f"   • Regime: {regime}")
    print(f"   • DEFCON: {defcon}/5")
    print(f"   • Directive: {report.get('final_directive', 'PROCEED')}")
    print(f"   • Allocations Updated: {'Yes' if allocations else 'No'}")
    print()

if __name__ == "__main__":
    main()




