#!/usr/bin/env python3
"""
Summarise backtest results into Markdown reports.
Called by nightly-backtest.yml workflow.
"""
import argparse
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


def parse_backtest_output(file_path: Path) -> Optional[Dict]:
    """Parse backtest output text file and extract metrics."""
    try:
        content = file_path.read_text()
        
        # Extract key metrics using regex
        metrics = {}
        
        # Initial Capital
        match = re.search(r'Initial Capital:\s+₹([\d,]+\.?\d*)', content)
        if match:
            metrics['initial_capital'] = float(match.group(1).replace(',', ''))
        
        # Final Capital
        match = re.search(r'Final Capital:\s+₹([\d,]+\.?\d*)', content)
        if match:
            metrics['final_capital'] = float(match.group(1).replace(',', ''))
        
        # Total Return
        match = re.search(r'Total Return:\s+₹([\d,]+\.?\d*)\s+\(([\d.]+)%\)', content)
        if match:
            metrics['total_return'] = float(match.group(1).replace(',', ''))
            metrics['total_return_pct'] = float(match.group(2))
        
        # Max Drawdown
        match = re.search(r'Max Drawdown:\s+([\d.]+)%', content)
        if match:
            metrics['max_drawdown_pct'] = float(match.group(1))
        
        # Trades
        match = re.search(r'Total Trades:\s+(\d+)', content)
        if match:
            metrics['total_trades'] = int(match.group(1))
        
        match = re.search(r'Wins:\s+(\d+)', content)
        if match:
            metrics['wins'] = int(match.group(1))
        
        match = re.search(r'Losses:\s+(\d+)', content)
        if match:
            metrics['losses'] = int(match.group(1))
        
        match = re.search(r'Win Rate:\s+([\d.]+)%', content)
        if match:
            metrics['win_rate'] = float(match.group(1))
        
        # Profit Factor
        match = re.search(r'Profit Factor:\s+([\d.]+)', content)
        if match:
            metrics['profit_factor'] = float(match.group(1))
        
        return metrics if metrics else None
        
    except Exception as e:
        print(f"⚠️ Failed to parse {file_path}: {e}")
        return None


def generate_summary_markdown(
    date: str,
    nifty_metrics: Optional[Dict],
    banknifty_metrics: Optional[Dict],
    output_path: Path
) -> None:
    """Generate Markdown summary report."""
    
    lines = [
        f"# Nightly Backtest Summary - {date}",
        "",
        f"**Generated:** {datetime.now().isoformat()}",
        "",
        "## Overview",
        "",
    ]
    
    if nifty_metrics:
        lines.extend([
            "### NIFTY",
            "",
            f"- **Initial Capital:** ₹{nifty_metrics.get('initial_capital', 0):,.0f}",
            f"- **Final Capital:** ₹{nifty_metrics.get('final_capital', 0):,.0f}",
            f"- **Total Return:** {nifty_metrics.get('total_return_pct', 0):.2f}%",
            f"- **Max Drawdown:** {nifty_metrics.get('max_drawdown_pct', 0):.2f}%",
            f"- **Total Trades:** {nifty_metrics.get('total_trades', 0)}",
            f"- **Win Rate:** {nifty_metrics.get('win_rate', 0):.2f}%",
            f"- **Profit Factor:** {nifty_metrics.get('profit_factor', 0):.2f}",
            "",
        ])
    else:
        lines.append("⚠️ NIFTY backtest data not available")
        lines.append("")
    
    if banknifty_metrics:
        lines.extend([
            "### BANKNIFTY",
            "",
            f"- **Initial Capital:** ₹{banknifty_metrics.get('initial_capital', 0):,.0f}",
            f"- **Final Capital:** ₹{banknifty_metrics.get('final_capital', 0):,.0f}",
            f"- **Total Return:** {banknifty_metrics.get('total_return_pct', 0):.2f}%",
            f"- **Max Drawdown:** {banknifty_metrics.get('max_drawdown_pct', 0):.2f}%",
            f"- **Total Trades:** {banknifty_metrics.get('total_trades', 0)}",
            f"- **Win Rate:** {banknifty_metrics.get('win_rate', 0):.2f}%",
            f"- **Profit Factor:** {banknifty_metrics.get('profit_factor', 0):.2f}",
            "",
        ])
    else:
        lines.append("⚠️ BANKNIFTY backtest data not available")
        lines.append("")
    
    lines.extend([
        "## Notes",
        "",
        "- This is an automated summary generated by the nightly backtest workflow.",
        "- For detailed trade-by-trade analysis, review the full backtest output files.",
        "",
    ])
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(f"✅ Summary written to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Summarise backtest results")
    parser.add_argument(
        "--date",
        type=str,
        required=True,
        help="Date in YYYY-MM-DD format"
    )
    parser.add_argument(
        "--out",
        type=str,
        default="reports/backtests/summary.md",
        help="Output markdown file path"
    )
    
    args = parser.parse_args()
    
    reports_dir = Path("reports/backtests")
    
    # Find backtest output files for this date
    nifty_file = reports_dir / f"nifty_{args.date}.txt"
    banknifty_file = reports_dir / f"banknifty_{args.date}.txt"
    
    nifty_metrics = parse_backtest_output(nifty_file) if nifty_file.exists() else None
    banknifty_metrics = parse_backtest_output(banknifty_file) if banknifty_file.exists() else None
    
    if not nifty_metrics and not banknifty_metrics:
        print("⚠️ No backtest data found for date:", args.date)
        return
    
    generate_summary_markdown(
        date=args.date,
        nifty_metrics=nifty_metrics,
        banknifty_metrics=banknifty_metrics,
        output_path=Path(args.out)
    )


if __name__ == "__main__":
    main()

