name: Actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/*.yml'
      - '**/*.yaml'
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a6376e9db8  # v4.1.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@186764204cf02529b48cf1f75ddd7c74c65989f4  # v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter

